% g729 : g729 codec
% ITU-T C language source edited by chinatsu MIYAUCHI
% 29 Apr. 2010. Ver.1.0
% function [ret] = g729( InFile, Outfile, Transf)
% INPUT-----------------------------------------------------------
% InFile      is the name of the file to be processed
% OutFile     is the name with the processed data
% Transf      is the desired conversion on the input file:
%              [e], encode
%              [d], decode
%              [ed], encode -> decode
%              default=[ed]
% OUTPUT-----------------------------------------------------------
% ret        : error code
%              0 = normal exit
%              other = error 

function [ret] = g729( InFile, Outfile, Transf)

% 引数が足りない場合、ヘルプ表示して終了
if (nargin < 2)
	help g729;
	return;
end;

%引数省略時はenc&decで
if (nargin == 2)
	Transf = 'ed';
end;

%毎回コンパイルしたくない時の判定文
%if( exist('g729mex','file') == 0 )

%MEXコンパイル開始
mex g729mex.c ...
-O coder_m.c ...
-O acelp_co.c ...
-O basic_op.c ...
-O bits.c ...
-O cod_ld8k.c ...
-O coder.c ...
-O decoder_m.c ...
-O de_acelp.c ...
-O dec_gain.c ...
-O dec_lag3.c ...
-O dec_ld8k.c ...
-O dspfunc.c ...
-O filter.c ...
-O gainpred.c ...
-O lpc.c ...
-O lpcfunc.c ...
-O lspgetq.c ...
-O oper_32b.c ...
-O p_parity.c ...
-O pitch.c ...
-O pre_proc.c ...
-O pred_lt3.c ...
-O pwf.c ...
-O qua_gain.c ...
-O qua_lsp.c ...
-O tab_ld8k.c ...
-O util.c ...
-O lspdec.c ...
-O post_pro.c ...
-O pst.c ...;

%end;

ret = g729mex( Transf,  InFile, Outfile)

return;
