% make g729enc
mex mexdecoder.c ...
 basic_op.c ...
 bits.c ...
 de_acelp.c ...
 dec_gain.c ...
 dec_lag3.c ...
 dec_ld8k.c ...
 dspfunc.c ...
 filter.c ...
 gainpred.c ...
 lpcfunc.c ...
 lspdec.c ...
 lspgetq.c ...
 oper_32b.c ...
 p_parity.c ...
 post_pro.c ...
 pred_lt3.c ...
 pst.c ...
 tab_ld8k.c ...
 util.c ...

