% make g729enc ----2010.04.19----
% �R���p�C������t�@�C���������̂�m�t�@�C���ɂ��Ă݂��B
% g792�f�B���N�g���ɓ���MATLAB��� menc ���邾���B

mex mexcoder.c ...
-O acelp_co.c ...
-O basic_op.c ...
-O bits.c ...
-O cod_ld8k.c ...
-O coder.c ...
-O dspfunc.c ...
-O filter.c ...
-O gainpred.c ...
-O lpc.c ...
-O lpcfunc.c ...
-O lspgetq.c ...
-O oper_32b.c ...
-O p_parity.c ...
-O pitch.c ...
-O pre_proc.c ...
-O pred_lt3.c ...
-O pwf.c ...
-O qua_gain.c ...
-O qua_lsp.c ...
-O tab_ld8k.c ...
-O util.c ...
 
